import { useState } from 'react'
import type { Item, Part } from '../lib/types'

export default function GeneratedQuestion({ item }: { item: Item }) {
  const [showAnswers, setShowAnswers] = useState(false)
  const [showScheme, setShowScheme] = useState(false)

  return (
    <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-sm">
      {/* Marks badge, like a real paper's right margin. */}
      <div className="flex items-start justify-between gap-4">
        <p className="whitespace-pre-line font-medium leading-relaxed">
          {item.stem}
        </p>
        <span className="shrink-0 rounded-md border border-[var(--border)] px-2 py-1 text-xs text-[var(--muted)]">
          {item.total_marks} {item.total_marks === 1 ? 'mark' : 'marks'}
        </span>
      </div>

      {item.diagram && (
        <figure className="my-5">
          <div
            className="mx-auto max-w-[300px] text-[var(--text)]"
            role="img"
            aria-label={item.diagram.alt}
            // SVG is generated by our own backend, not user input.
            dangerouslySetInnerHTML={{ __html: item.diagram.svg }}
          />
          {item.diagram.not_to_scale && (
            <figcaption className="mt-1 text-center text-xs italic text-[var(--muted)]">
              Diagram NOT accurately drawn
            </figcaption>
          )}
        </figure>
      )}

      <div className="space-y-4">
        {item.parts.map((part, i) => (
          <PartBlock
            key={i}
            part={part}
            showAnswer={showAnswers}
            showScheme={showScheme}
          />
        ))}
      </div>

      <div className="mt-6 flex flex-wrap gap-2 border-t border-[var(--border)] pt-4">
        <Toggle on={showAnswers} onClick={() => setShowAnswers((v) => !v)}>
          {showAnswers ? 'Hide answer' : 'Show answer'}
        </Toggle>
        <Toggle on={showScheme} onClick={() => setShowScheme((v) => !v)}>
          {showScheme ? 'Hide mark scheme' : 'Show mark scheme'}
        </Toggle>
      </div>

      <p className="mt-4 text-xs text-[var(--muted)]">
        {item.metadata.topic} · {item.metadata.spec_ref} ·{' '}
        {item.calculator ? 'Calculator' : 'Non-calculator'} ·{' '}
        {item.tier === 'higher' ? 'Higher' : 'Foundation'}
      </p>
    </article>
  )
}

function PartBlock({
  part,
  showAnswer,
  showScheme,
}: {
  part: Part
  showAnswer: boolean
  showScheme: boolean
}) {
  return (
    <div>
      <div className="flex items-start justify-between gap-4">
        <p className="leading-relaxed">
          {part.label && (
            <span className="mr-2 font-semibold">({part.label})</span>
          )}
          {part.prompt}
        </p>
        <span className="shrink-0 text-sm text-[var(--muted)]">
          ({part.marks})
        </span>
      </div>

      {showAnswer && (
        <div className="mt-2 rounded-lg bg-[var(--hover)] p-3 text-sm">
          <p className="font-semibold">Answer: {part.answer}</p>
          <pre className="mt-1 whitespace-pre-wrap font-sans text-[var(--muted)]">
            {part.working}
          </pre>
        </div>
      )}

      {showScheme && (
        <ul className="mt-2 space-y-1 text-sm">
          {part.mark_scheme.map((step, i) => (
            <li key={i} className="flex gap-2">
              <span className="font-mono font-semibold">{step.code}</span>
              <span className="text-[var(--muted)]">
                {step.description}
                {step.working ? ` — ${step.working}` : ''}
              </span>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

function Toggle({
  on,
  onClick,
  children,
}: {
  on: boolean
  onClick: () => void
  children: React.ReactNode
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={on}
      className={
        'rounded-full px-4 py-2 text-sm font-medium transition ' +
        (on
          ? 'bg-[var(--accent)] text-[var(--accent-text)]'
          : 'border border-[var(--border)] text-[var(--text)] hover:border-[var(--muted)]')
      }
    >
      {children}
    </button>
  )
}
