"""users and stripe_events

Revision ID: 0001_initial
Revises:
Create Date: 2026-10-05

Hand-written rather than autogenerated, so it does not depend on having had a
live database to diff against. Kept in lockstep with app/models.py — there is a
test that fails if the two drift.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("clerk_user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("plan", sa.Text(), server_default="free", nullable=False),
        sa.Column("subscription_status", sa.Text(), nullable=True),
        sa.Column("stripe_customer_id", sa.Text(), nullable=True),
        sa.Column("stripe_subscription_id", sa.Text(), nullable=True),
        sa.Column(
            "total_generations", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "day_generations", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("day_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plan IN ('free', 'monthly')", name=op.f("ck_users_plan")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("clerk_user_id", name=op.f("uq_users_clerk_user_id")),
        sa.UniqueConstraint(
            "stripe_customer_id", name=op.f("uq_users_stripe_customer_id")
        ),
        sa.UniqueConstraint(
            "stripe_subscription_id", name=op.f("uq_users_stripe_subscription_id")
        ),
    )
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stripe_events")),
    )


def downgrade() -> None:
    op.drop_table("stripe_events")
    op.drop_table("users")
