import { Link } from 'react-router-dom'
import BackLink from '../components/BackLink'

// The text below is a verbatim transcription of docs/terms.md, which is the
// source of truth: change that file first, then this page.
const linkClass =
  'underline underline-offset-2 transition-colors hover:text-[var(--text)]'

export default function Terms() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-8">
      <BackLink to="/">Home</BackLink>
      <h1 className="mt-4 text-2xl font-semibold tracking-tight">
        Terms of service
      </h1>
      <p className="mt-3 text-[var(--muted)]">Last updated: 8 October 2026.</p>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">Who we are</h2>
      <p className="mt-3 text-[var(--muted)]">
        ExamPaper is run by Sshubhan Kammari, a sole trader in England.
      </p>
      <p className="mt-3 text-[var(--muted)]">
        Address: 54 Halidon Rise, Harold Wood, Romford RM3 0YL
      </p>
      <p className="mt-3 text-[var(--muted)]">
        Contact:{' '}
        <a href="mailto:ksshubhan@gmail.com" className={linkClass}>
          ksshubhan@gmail.com
        </a>
      </p>
      <p className="mt-3 text-[var(--muted)]">
        By creating an account or subscribing, you agree to these terms. Please
        read them with our privacy policy:{' '}
        <Link to="/privacy" className={linkClass}>
          /privacy
        </Link>
      </p>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        What ExamPaper is
      </h2>
      <p className="mt-3 text-[var(--muted)]">
        ExamPaper generates practice papers and worksheets in the style of GCSE
        exam papers, each with a mark scheme. It currently covers Edexcel GCSE
        Maths, Foundation and Higher.
      </p>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          Questions are generated by computer. They are not copied from real
          past papers.
        </li>
        <li>
          Answers are checked by computer, but mistakes can still happen. If you
          find one, please email us.
        </li>
        <li>
          ExamPaper is not affiliated with or endorsed by Pearson Education Ltd
          or any exam board.
        </li>
        <li>
          Practice papers help with revision, but we cannot promise any grade or
          exam result.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Your account
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          The account should be held by an adult, usually a parent or guardian.
          You must be 18 or over to create one.
        </li>
        <li>
          Keep your sign-in details secure. You are responsible for what happens
          on your account.
        </li>
        <li>
          One account per person. Do not share your sign-in with anyone else.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Plans and price
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>Free: one paper or worksheet in total.</li>
        <li>
          Unlimited: £5 a month, for as many papers and worksheets as you need,
          subject to fair use.
        </li>
        <li>
          Fair use: up to 10 papers or worksheets a day (UK time). Other fair
          use limits apply to protect the service.
        </li>
        <li>
          Downloading a paper you have already generated again does not count as
          a new paper.
        </li>
        <li>
          A paper or worksheet that fails to generate does not count towards
          your limit.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Billing, renewal and cancelling
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>Payments are taken by Stripe. We never see your card details.</li>
        <li>Unlimited renews automatically every month until you cancel.</li>
        <li>
          You can cancel at any time from your account page (
          <Link to="/account" className={linkClass}>
            /account
          </Link>
          ) by choosing Manage subscription.
        </li>
        <li>
          When you cancel, you keep Unlimited until the end of the month you
          have paid for. No further payments are taken.
        </li>
        <li>
          If we change the price, we will email you at least 30 days before the
          new price applies. You can cancel before then.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Refunds and your right to cancel
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          If you change your mind, you can get a full refund within 14 days of
          starting a subscription. Email us to ask.
        </li>
        <li>
          After those 14 days, payments are not refunded, including for part of
          a month. Cancelling stops future payments.
        </li>
        <li>
          If something goes wrong on our side, such as the service not working,
          email us and we will put it right. This does not affect your legal
          rights.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Using ExamPaper fairly
      </h2>
      <p className="mt-3 text-[var(--muted)]">You must not:</p>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          use scripts, bots or other automated tools to access ExamPaper or
          generate papers;
        </li>
        <li>
          try to get round the limits on your plan, for example by creating
          extra accounts for more free papers;
        </li>
        <li>
          try to break, overload or gain unauthorised access to the service.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Sharing papers
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          Papers and worksheets are for use by you and your own household, for
          example a parent printing papers for their children.
        </li>
        <li>
          You must not sell, publish, upload or share them outside your
          household. This includes use by tutors with their students and by
          schools with their classes.
        </li>
        <li>
          Each PDF shows the email address of the account it was generated for.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Who owns what
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          We own ExamPaper, including the website, its code and the papers it
          generates.
        </li>
        <li>
          We give you permission to use the papers you generate as these terms
          allow, for as long as you keep them.
        </li>
        <li>
          Exam board names are used only to describe which exams the papers are
          for.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Availability and changes to the service
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          We aim to keep ExamPaper running, but we cannot promise it will always
          be available or free of errors.
        </li>
        <li>
          We may change or remove features. If we ever close ExamPaper, we will
          cancel all subscriptions so no further payments are taken, and tell
          you by email.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Our responsibility to you
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          Nothing in these terms affects your legal rights as a consumer,
          including under the Consumer Rights Act 2015.
        </li>
        <li>
          We are responsible for loss or damage you suffer that is a foreseeable
          result of us breaking these terms or failing to use reasonable care
          and skill.
        </li>
        <li>
          We are not responsible for loss or damage that was not foreseeable, or
          for any business loss.
        </li>
        <li>
          Nothing in these terms limits our responsibility for death or personal
          injury caused by our negligence, or for fraud.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Suspending or closing your account
      </h2>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-[var(--muted)]">
        <li>
          We may suspend or close your account if you break these terms. We will
          tell you by email why.
        </li>
        <li>
          You can ask us to delete your account at any time by emailing{' '}
          <a href="mailto:ksshubhan@gmail.com" className={linkClass}>
            ksshubhan@gmail.com
          </a>
          . See{' '}
          <Link to="/privacy" className={linkClass}>
            /privacy
          </Link>{' '}
          for what we delete and when.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        The law that applies
      </h2>
      <p className="mt-3 text-[var(--muted)]">
        These terms are governed by the law of England and Wales. If you live in
        Scotland or Northern Ireland, you can also bring a claim in your local
        courts.
      </p>

      <h2 className="mt-8 text-lg font-semibold tracking-tight">
        Changes to these terms
      </h2>
      <p className="mt-3 text-[var(--muted)]">
        We may update these terms. If a change is significant, we will email you
        before it applies. The date at the top shows when they were last
        changed.
      </p>
    </div>
  )
}
